manifest_version = 1

[project]
name = "ore"
private = true

[install]
allow_outside_project = true

[sdk]
targets = ["typescript", "rust"]

[sdk.typescript]
output_dir = "../../examples/ore-react/src/generated"
package = "@usearete/react"

[sdk.rust]
output_dir = "../../examples/ore-rust/src/generated/ore"
module_mode = true

[authoring.stacks.ore]
manifest = "./.arete/OreStream.stack-manifest.json"
artifact_roots = ["./.arete"]
deployment_name = "ore"

[dependencies.stacks.ore]
source = { workspace = "ore" }
