export { AreteProvider, useAreteContext, useConnectionState, useView, useEntity } from './provider';
export { useArete } from './stack';
export { ZustandAdapter } from './zustand-adapter';
export type { AreteStore } from './zustand-adapter';

export { useInstructionMutation } from './hooks';
export type { UseMutationOptions, UseMutationResult, MutationStatus } from './hooks';

export {
  ConnectionManager,
  FrameProcessor,
  MemoryAdapter,
  Arete,
  ReadRequestError,
  SubscriptionRegistry,
  withPrograms,
  parseFrame,
  parseFrameFromBlob,
  isValidFrame,
  isSnapshotFrame,
  AreteError,
  DEFAULT_CONFIG,
  DEFAULT_MAX_ENTRIES_PER_VIEW,
  resolveAccounts,
  validateAccountResolution,
  derivePda,
  createSeed,
  createPublicKeySeed,
  serializeInstructionData,
  parseInstructionError,
  formatProgramError,
  InstructionError,
  buildInstruction,
  executeInstruction,
  createInstructionHandler,
  createInstructionExecutor,
} from '@usearete/sdk';

export type {
  StorageAdapter,
  UpdateCallback,
  RichUpdateCallback,
  StorageAdapterConfig,
  FrameProcessorConfig,
  ConnectOptions,
  AreteOptionsWithStorage,
  ConnectedArete,
  InstructionExecutor,
  MergeProgramMaps,
  EntityFrame,
  SnapshotFrame,
  SnapshotEntity,
  Frame,
  FrameMode,
  FrameOp,
  ConnectionState,
  Update,
  RichUpdate,
  Subscription,
  AreteOptions,
  WalletAdapter,
  WalletState,
  WalletConnectOptions,
  AccountCategory,
  AccountMeta,
  PdaConfig,
  PdaSeed,
  ResolvedAccount,
  ResolvedAccounts,
  AccountResolutionResult,
  AccountResolutionOptions,
  ArgSchema,
  ArgType,
  ConfirmationLevel,
  SendOptions,
  SendResult,
  BuildOptions,
  ExecuteOptions,
  ExecutionResult,
  ProgramError,
  ErrorMetadata,
  InstructionHandler,
  InstructionHandlerConfig,
  PreparedOperation,
  PreparedInstruction,
  PreparedTransactionInstruction,
  PreparedTransaction,
  PreparedFlow,
  OperationReceiptFor,
  OperationExecutionOptions,
  TypedInstruction,
  StackWithAttachedPrograms,
  BuiltInstruction,
  BuiltAccountMeta,
  TransactionOptions,
  AuthConfig,
} from '@usearete/sdk';

export type {
  TransactionDefinition,
  StackDefinition,
  AreteConfig,
  ClientLookupOptions,
  UseAreteOptions,
  ViewHookOptions,
  ViewHookResult,
  ListParams,
  ListParamsBase,
  ListParamsSingle,
  ListParamsMultiple,
  UseMutationReturn,
  StateViewHook,
  ListViewHook,
  ViewMode,
  ViewDef,
  ViewGroup,
  Schema,
} from './types';
