"""Generated Arete stack binding for `token-balances`.

Generated by the Arete interpreter (arete-sdk {{ARETE_VERSION}}); do not edit.
"""

from __future__ import annotations


from arete.stack import StackDef, StackEndpoints

from . import models, programs, views
from .models import *  # noqa: F401,F403
from .programs import *  # noqa: F401,F403
from .views import *  # noqa: F401,F403

TOKEN_BALANCES_STACK: StackDef = StackDef(
    name="token-balances",
    endpoints=StackEndpoints(
        ws="",  # TODO: Set URL after first deployment in arete.toml
    ),
    views=views.VIEWS,
    programs=programs.PROGRAMS,
    program_reads=programs.PROGRAM_READS,
)

__all__ = [
    "TOKEN_BALANCES_STACK",
    *models.__all__,
    *programs.__all__,
    *views.__all__,
]
