"""Send a transaction-V1 (SIMD-0385) transaction through the Arete relay.

    pip install 'arete-sdk[solana]'
    python examples/solana_v1.py

The V1 budget and priority fee are typed options, not hand-rolled
ComputeBudget instructions: the adapter rejects those so one code path owns the
budget for every transaction version. Swap ``transaction_version`` to ``0`` or
``"legacy"`` and the same options compile to ComputeBudget instructions
instead -- with ``compute_unit_price_micro_lamports`` replacing
``priority_fee_lamports``, which is V1-only.
"""

import asyncio
import os

from solders.keypair import Keypair

import arete
from arete.adapters.solders import SoldersAdapterConfig, SoldersWalletAdapter
from arete.instructions import BuiltAccountMeta, BuiltInstruction
from arete.operations import TransactionExecutionError
from arete.rpc import RpcTransactionTransport
from arete.wallet import SendOptions, TransactionResourceOptions

# Generated by `a4 sdk create --python`, exactly as in the README quick start.
from my_generated_stack import ORE_STREAM_STACK  # type: ignore[import-not-found]

MEMO_PROGRAM = "MemoSq4gqABAXKb96qnH8TysNcWxMyWCqXgDLGmfcHr"


def memo(signer: str, note: str) -> BuiltInstruction:
    """A memo instruction; a real app builds these from its generated stack."""
    return BuiltInstruction(
        program_id=MEMO_PROGRAM,
        accounts=[
            BuiltAccountMeta(pubkey=signer, is_signer=True, is_writable=True)
        ],
        data=note.encode(),
    )


async def main() -> None:
    keypair = Keypair.from_base58_string(os.environ["SOLANA_KEYPAIR"])

    async with await arete.Arete.connect(
        ORE_STREAM_STACK,
        auth=arete.AuthConfig(publishable_key=os.environ["ARETE_PUBLISHABLE_KEY"]),
    ) as a4:
        # Arete by default. Set SOLANA_RPC_URL and the same adapter runs
        # against that node instead -- same compiler, same budget planner,
        # same inspection, signing and confirmation above it.
        rpc_url = os.environ.get("SOLANA_RPC_URL")
        wallet = SoldersWalletAdapter(
            SoldersAdapterConfig(
                keypair=keypair,
                # Under "auto" the client passes its own relay on every send
                # and this is the fallback for direct adapter use; under
                # "direct" it wins even with a connected client.
                transport=(
                    RpcTransactionTransport(rpc_url) if rpc_url else a4.transactions
                ),
                transport_selection="direct" if rpc_url else "auto",
                transaction_version=1,
                # V1 always resolves its two budgets before signing; this also
                # measures the legacy/v0 ceilings a send leaves unset.
                estimate_resources=True,
                confirmation_level="confirmed",
            )
        )

        instruction = memo(str(keypair.pubkey()), "hello from transaction v1")

        # Unsigned inspection: fee, logs and the loaded-accounts size a V1
        # budget needs. Never signs, never submits, never prompts.
        inspection = await wallet.inspect_transaction(
            [instruction], SendOptions(transaction_version=1)
        )
        print("fee lamports:", inspection.fee_lamports)
        print("compute units:", inspection.compute_units_consumed)
        print("loaded accounts data size:", inspection.loaded_accounts_data_size)
        print("wire bytes:", inspection.extra["wireBytes"])
        if inspection.error is not None:
            print("simulation failed:", inspection.error)
            return

        send = SendOptions(
            transaction_version=1,
            confirmation_level="confirmed",
            resources=TransactionResourceOptions(
                # Total lamports, V1 only. Legacy/v0 use
                # compute_unit_price_micro_lamports (per compute unit) instead.
                priority_fee_lamports=10_000,
                heap_size=64 * 1024,
            ),
        )

        try:
            result = await a4.transaction([instruction], wallet=wallet, send=send)
        except TransactionExecutionError as error:
            # Outcomes are data: confirmed | not-submitted | submitted-unknown
            # | chain-failed, each with the phase that produced it. A
            # submitted-unknown carries the signature to reconcile with, and is
            # never a reason to resend.
            outcome = error.outcome
            print(f"{outcome.status} in {outcome.phase}: {outcome.message}")
            if outcome.signature:
                print("reconcile signature:", outcome.signature)
            return

        print("confirmed:", result.signature, "slot", result.slot)


if __name__ == "__main__":
    asyncio.run(main())
