"""Generated Arete stack binding for `OreStream`.

Generated by the Arete interpreter (arete-sdk 0.4); do not edit.
"""

from __future__ import annotations

from arete.stack import StackDef, StackEndpoints

from . import models, programs, views
from .models import *  # noqa: F401,F403
from .programs import *  # noqa: F401,F403
from .views import *  # noqa: F401,F403

ORE_STREAM_STACK: StackDef = StackDef(
    name="ore-stream",
    endpoints=StackEndpoints(
        ws="wss://ore.stack.arete.run",
        http="https://ore.stack.arete.run",
    ),
    views=views.VIEWS,
    programs=programs.PROGRAMS,
    program_reads=programs.PROGRAM_READS,
)

__all__ = [
    "ORE_STREAM_STACK",
    *models.__all__,
    *programs.__all__,
    *views.__all__,
]
