"""Generated Arete stack binding for `my.stack`.

Generated by the Arete interpreter (arete-sdk 0.20.1); do not edit.
"""

from __future__ import annotations


from arete.stack import StackDef, StackEndpoints

from . import models, programs, views
from .models import *  # noqa: F401,F403
from .programs import *  # noqa: F401,F403
from .views import *  # noqa: F401,F403

MY_STACK_STACK: StackDef = StackDef(
    name="my.stack",
    endpoints=StackEndpoints(
        ws="",  # TODO: Set URL after first deployment in arete.toml
    ),
    views=views.VIEWS,
    programs=programs.PROGRAMS,
    program_reads=programs.PROGRAM_READS,
)

__all__ = [
    "MY_STACK_STACK",
    *models.__all__,
    *programs.__all__,
    *views.__all__,
]
