"""Program SDK `vault` of the `VaultStream` stack.

The generated program with its program package's own extension applied, laid
out like the standalone `vault` program package so the extension's relative
imports (`.programs`, `.models`, sibling files) resolve unchanged.

Generated by the Arete interpreter (arete-sdk {{ARETE_VERSION}}); do not edit.
"""

from . import models, programs  # noqa: F401

# Hand-authored program package extension (staged from extensions.json; not
# generated). Its entry exports PROGRAM_EXTENSIONS, applied to the generated
# program definition; the package release identity is stamped after it.
from . import vault_math  # noqa: F401,E402
from . import extensions  # noqa: F401,E402
from arete import extend_program as _extend_program  # noqa: E402
from arete import program_extensions_of as _program_extensions_of  # noqa: E402
from arete import with_program_identity as _with_program_identity  # noqa: E402

VAULT_PROGRAM = _extend_program(
    programs.VAULT_PROGRAM, **_program_extensions_of(extensions)
)
VAULT_PROGRAM = _with_program_identity(
    VAULT_PROGRAM,
    package_release_hash=programs.VAULT_PACKAGE_RELEASE_HASH,
)
