"""The stack's generated `models` module, where the `vault` program package
extension imports it (`.models`).

Generated by the Arete interpreter; do not edit.
"""

from ...models import *  # noqa: F401,F403
from ...models import __all__  # noqa: F401

# The program's account models, under the names the standalone program package
# gives them.
from ...models import VaultVault as Vault  # noqa: F401,E402
from ...models import vault_vault_from_wire as vault_from_wire  # noqa: F401,E402
from ...models import (  # noqa: F401,E402
    vault_vault_patch_from_wire as vault_patch_from_wire,
)

__all__ = [
    *__all__,
    "Vault",
    "vault_from_wire",
    "vault_patch_from_wire",
]
