"""The stack's generated `programs` module, where the `vault` program package
extension imports it (`.programs`).

Generated by the Arete interpreter; do not edit.
"""

from ...programs import *  # noqa: F401,F403
from ...programs import __all__  # noqa: F401
