"""Generated Arete stack binding for `VaultStream`.

Generated by the Arete interpreter (arete-sdk {{ARETE_VERSION}}); do not edit.
"""

from __future__ import annotations

import json
from arete.gateway import HostedSolanaGatewayBindings

from arete.stack import StackDef, StackEndpoints, StackRelease

from . import models, programs, views
from .models import *  # noqa: F401,F403
from .programs import *  # noqa: F401,F403
from .views import *  # noqa: F401,F403

# Program SDKs that carry their program package's own extension (staged under
# program_sdks/; the extensions are not generated).
from .program_sdks import vault as _vault_program_sdk

VAULT_PROGRAM = _vault_program_sdk.VAULT_PROGRAM
PROGRAMS = {
    **programs.PROGRAMS,
    "vault": VAULT_PROGRAM,
}

VAULT_STREAM_STACK: StackDef = StackDef(
    name="vault-stream",
    endpoints=StackEndpoints(
        ws="wss://vault.stack.example.test",
        http="https://vault.stack.example.test",
    ),
    views=views.VIEWS,
    programs=PROGRAMS,
    program_reads=programs.PROGRAM_READS,
    gateway=HostedSolanaGatewayBindings.from_dict(json.loads("{\"chain\":{\"auth\":{\"acceptedKeyClasses\":[\"publishable\",\"secret\"],\"audience\":\"arete:solana-gateway\",\"jwksUrl\":\"https://api.example.test/.well-known/jwks.json\",\"mode\":\"signed_session\",\"required\":true,\"scopes\":[\"read\"],\"sessionEndpoint\":\"https://api.example.test/ws/sessions\",\"targetId\":\"sgb_00000000000000000000000000000001\",\"targetKind\":\"solana-gateway-binding\",\"tokenTransport\":\"bearer\",\"transactionEntitlementRequired\":false},\"authPolicy\":\"signed_session\",\"cluster\":\"mainnet-beta\",\"endpoint\":\"https://solana.example.test/gateway/\",\"region\":\"us-west-1\",\"solanaGatewayBindingId\":\"sgb_00000000000000000000000000000001\"},\"transactions\":{\"auth\":{\"acceptedKeyClasses\":[\"publishable\",\"secret\"],\"audience\":\"arete:solana-gateway\",\"jwksUrl\":\"https://api.example.test/.well-known/jwks.json\",\"mode\":\"signed_session\",\"required\":true,\"scopes\":[\"transaction:inspect\",\"transaction:send\"],\"sessionEndpoint\":\"https://api.example.test/ws/sessions\",\"targetId\":\"sgb_00000000000000000000000000000001\",\"targetKind\":\"solana-gateway-binding\",\"tokenTransport\":\"bearer\",\"transactionEntitlementRequired\":true},\"authPolicy\":\"signed_session\",\"cluster\":\"mainnet-beta\",\"endpoint\":\"https://solana.example.test/gateway/\",\"region\":\"us-west-1\",\"solanaGatewayBindingId\":\"sgb_00000000000000000000000000000001\"}}")),
    release=StackRelease(
        stack_manifest_hash="arete:h1:stack-manifest:sha256:53809b392576092808edfbf619ec0b9b4174373a84c2dac843af4a71537fbb72",
        live_alias="live",
    ),
)

__all__ = [
    "VAULT_STREAM_STACK",
    *models.__all__,
    *programs.__all__,
    *views.__all__,
]

# Hand-authored stack extension (staged from extensions.json; not generated).
# Its entry exports STACK_EXTENSIONS, applied to the generated stack definition.
from . import extensions  # noqa: F401,E402
from arete import extend_stack as _extend_stack  # noqa: E402
from arete import stack_extensions_of as _stack_extensions_of  # noqa: E402

VAULT_STREAM_STACK = _extend_stack(VAULT_STREAM_STACK, **_stack_extensions_of(extensions))
