"""Generated standalone program SDK for `vault`.

Generated by the Arete interpreter (arete-sdk {{ARETE_VERSION}}); do not edit.
`PROGRAMS` and `PROGRAM_READS` compose directly with `arete.create_session`.
"""

from . import models, programs
from .models import *  # noqa: F401,F403
from .programs import *  # noqa: F401,F403

__all__ = [
    *models.__all__,
    *programs.__all__,
]

# Hand-authored program package extension (staged from extensions.json; not
# generated). Its entry exports PROGRAM_EXTENSIONS, applied to the generated
# program definition; the package release identity is stamped after it.
from . import vault_math  # noqa: F401,E402
from . import extensions  # noqa: F401,E402
from arete import extend_program as _extend_program  # noqa: E402
from arete import program_extensions_of as _program_extensions_of  # noqa: E402
from arete import with_program_identity as _with_program_identity  # noqa: E402

VAULT_PROGRAM = _extend_program(
    programs.VAULT_PROGRAM, **_program_extensions_of(extensions)
)
VAULT_PROGRAM = _with_program_identity(
    VAULT_PROGRAM,
    package_release_hash=programs.VAULT_PACKAGE_RELEASE_HASH,
)
PROGRAMS = {**PROGRAMS, "vault": VAULT_PROGRAM}
